### ISSUE TITLE
Feature: Ability to sign as well as encrypt

### ISSUE THREAD

**Issue by h3lix1** [tehbmar/easy-keybase.io-encryption-extension#2]
The ability to sign a message would be great without requiring encryption.

**Comment by 0x4445565A** [comment]
Hey @h3lix1 I have had this requested on the Google chrome store as well and I think I'm going to implement it.  Currently I'm just trying to figure out the best way to do this because the key has to be on the keybase.io server and then the user has to unlock it client side with their password.  I'm thinking I might make it an optional feature that can be enabled with the google chrome options.

Currently the road block is figuring out how to properly load the private key from the server without also creating a login session with would be less than fun.

Probably going to grab the user object from the username and use triplesec to decrypt it
https://keybase.io/docs/api/1.0/user_objects
https://keybase.io/triplesec

**Comment by 0x4445565A** [comment]
So I have worked on this today through out the day and in order to get this to work I had to refactor the ugly way I created encrypted text etc.  It's a lot better, not perfect, but it works.

Currently you can now enable message signing with the google chrome extension options.  You can also input a default username to sign as.  After enabling signing the "sign" check box appears in the UI.  If enabled it will reveal a username and password field.  The password is used to unpack the key and the username is to pull the key from keybase in P3SKB format.  After that the message is encrypted, if username is provided, and then the message is signed with the unlocked private key.

The password is never sent out and all encrypting and decrypting is handled in JS client side.

Seems like it is working out pretty well.  If you could test it and let me know your results that would be fantastic!
